from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class CampaignInfo(BaseModel):
    CampaignId: Optional[str] = Field(None, description="Unique identifier for the campaign, generated by Office 365.")
    CampaignName: Optional[str] = Field(None, description="Name of the email campaign.")
    CampaignSubType: Optional[str] = Field(None, description="Contains more details about the campaign, like the brand being phished, or related malware campaigns, if available.")
    CampaignType: Optional[str] = Field(None, description="Category of the campaign.")
    NetworkMessageId: Optional[str] = Field(None, description="Unique identifier for the email, generated by Office 365.")
    RecipientEmailAddress: Optional[str] = Field(None, description="Email address of the recipient, or email address of the recipient after distribution list expansion.")
    ReportId: Optional[str] = Field(None, description="Unique identifier for the event.")
    SourceSystem: Optional[str] = Field(None, description="The type of agent the event was collected by. For example,OpsManagerfor Windows agent, either direct connect or Operations Manager,Linuxfor all Linux agents, orAzurefor Azure Diagnostics")
    TenantId: Optional[str] = Field(None, description="The Log Analytics workspace ID")
    TimeGenerated: Optional[datetime] = Field(None, description="Date and time (UTC) when the record was generated.")
    Type: Optional[str] = Field(None, description="The name of the table")
