from datetime import datetime
from typing import Any
from typing import Optional

from pydantic import BaseModel, Field


class CloudStorageAggregatedEvents(BaseModel):
    Timestamp: Optional[datetime] = Field(None, description="Date and time when the event was recorded")
    AccountApplicationId: Optional[str] = Field(None, description="The application ID associated with the storage access")
    AccountObjectId: Optional[str] = Field(None, description="The unique identifier of the object is making the storage access")
    AccountTenantId: Optional[str] = Field(None, description="The unique identifier of the Azure tenant")
    AccountType: Optional[int] = Field(None, description="The account type used")
    AccountUpn: Optional[str] = Field(None, description="The user principal name of the accessing user")
    ActionType: Optional[str] = Field(None, description="Type of action (aggregated logs)")
    AdditionalFields: Optional[Any] = Field(None, description="Additional information about the event in JSON array format")
    AnonymousSuccessfulOperations: Optional[int] = Field(None, description="The count of successful anonymous operations")
    AuthenticationType: Optional[str] = Field(None, description="The authentication method used to access the storage (for example, AccountKey, SAS, Oauth)")
    AzureResourceId: Optional[str] = Field(None, description="The Azure Resource ID of the storage account")
    AzureSubscriptionId: Optional[str] = Field(None, description="Unique identifier assigned to the Azure subscription")
    CityName: Optional[str] = Field(None, description="The name of the city from where the storage was accessed")
    ClientCloudPlatformName: Optional[str] = Field(None, description="The name of the cloud platform where the data center is located")
    ClientSystemServiceName: Optional[str] = Field(None, description="The name of the system service is in the data center")
    CountryName: Optional[str] = Field(None, description="The name of the country from where the storage was accessed")
    DataAggregationEndTime: Optional[datetime] = Field(None, description="The end time during which the data was aggregated")
    DataAggregationStartTime: Optional[datetime] = Field(None, description="The start time during which the data was aggregated")
    DataSource: Optional[str] = Field(None, description="The source of the aggregated logs")
    DistinctGetOperations: Optional[int] = Field(None, description="The count of distinct GET operations performed")
    FailedOperationsCount: Optional[int] = Field(None, description="The count of failed storage operations")
    FirstEventTimestamp: Optional[datetime] = Field(None, description="The timestamp of the first observed operation in the aggregation period")
    HasAnonymousResourceNotFoundFailures: Optional[bool] = Field(None, description="Indicates whether anonymous resource not found failures occurred")
    HashReputationMd5List: Optional[Any] = Field(None, description="A list of MD5 hash reputations for the accessed resources")
    IpAddress: Optional[str] = Field(None, description="The IP addresses from which the storage was accessed")
    IsKnownSuspiciousIp: Optional[bool] = Field(None, description="Indicates whether the IP address is known to be suspicious")
    IsPrivateIp: Optional[bool] = Field(None, description="Indicates whether the IP address is private")
    IsTorExitNode: Optional[bool] = Field(None, description="Indicates whether the IP address is a Tor exit node")
    LastEventTimestamp: Optional[datetime] = Field(None, description="The timestamp of the last observed operation in the aggregation period")
    Location: Optional[str] = Field(None, description="The location of the storage account (region)")
    OperationNamesList: Optional[Any] = Field(None, description="A list of storage operations performed (for example, CreateContainer, DeleteContainer)")
    OperationsCount: Optional[int] = Field(None, description="The total number of storage operations performed")
    ProvinceName: Optional[str] = Field(None, description="The name of the province or state from where the storage was accessed")
    ReportId: Optional[str] = Field(None, description="GUID to identify the record in the specific table")
    ResourceGroup: Optional[str] = Field(None, description="Name of the resource group where the storage account resides")
    ServiceType: Optional[str] = Field(None, description="Specifies the type of storage service (for example, Blob, ADLS Gen2, Files.REST, Files.SMB)")
    SourceSystem: Optional[str] = Field(None, description="The type of agent the event was collected by. For example,OpsManagerfor Windows agent, either direct connect or Operations Manager,Linuxfor all Linux agents, orAzurefor Azure Diagnostics")
    StorageAccount: Optional[str] = Field(None, description="The identifier for the storage account")
    StorageContainer: Optional[str] = Field(None, description="The identifier for the storage container")
    StorageFileShare: Optional[str] = Field(None, description="The identifier for the storage file share")
    SuccessfulOperationsCount: Optional[int] = Field(None, description="The count of successful storage operations")
    SuccessfulReadOperations: Optional[int] = Field(None, description="The count of successful read operations")
    SuspiciousUserAgentName: Optional[str] = Field(None, description="The name of the suspicious user agent accessing the storage")
    TenantId: Optional[str] = Field(None, description="The Log Analytics workspace ID")
    TimeGenerated: Optional[datetime] = Field(None, description="Date and time (UTC) when the record was generated")
    TotalResponseLength: Optional[int] = Field(None, description="The total response length of all GET operations during the aggregation period")
    Type: Optional[str] = Field(None, description="The name of the table")
    UserAgentHeader: Optional[str] = Field(None, description="Details of the user agent accessing the storage (for example, browser or application)")
