from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class DisruptionAndResponseEvents(BaseModel):
    Timestamp: Optional[datetime] = Field(None, description="Date and time when the event was recorded")
    ActionType: Optional[str] = Field(None, description="Type of disruption action taken")
    AuthenticationProtocol: Optional[str] = Field(None, description="Authentication protocol that the compromised user used to sign in")
    CompromisedAccountCount: Optional[int] = Field(None, description="Number of compromised accounts that are part of the policy")
    DataSources: Optional[str] = Field(None, description="Products or services that provided information for the event")
    DeviceId: Optional[str] = Field(None, description="Unique identifier for the device that reported the event")
    DeviceName: Optional[str] = Field(None, description="Name of the device that reported the event")
    DomainName: Optional[str] = Field(None, description="Domain name that the device that reported the event is joined to")
    FileName: Optional[str] = Field(None, description="Name of the file that the attacker attempted to access")
    InitiatingProcessFileName: Optional[str] = Field(None, description="Name of the process that triggered the block action")
    InitiatingProcessId: Optional[int] = Field(None, description="Process ID (PID) of the process that triggered that block action")
    InterfaceFriendlyName: Optional[str] = Field(None, description="Friendly name of the interface represented by the interface UUID")
    InterfaceUuid: Optional[str] = Field(None, description="Unique identifier (UUID) for the RPC interface that the attacker attempted to access")
    IpAddress: Optional[str] = Field(None, description="IP address that the attacker attempted to access")
    IsPolicyOn: Optional[bool] = Field(None, description="Indicates the current state of the policy on the device at the time of the disruption event")
    LogonId: Optional[int] = Field(None, description="Identifier for a logon session")
    LogonType: Optional[str] = Field(None, description="Type of logon session the user attempted")
    PolicyHash: Optional[str] = Field(None, description="Unique hash of the policy")
    PolicyId: Optional[str] = Field(None, description="Unique identifier for the policy")
    PolicyName: Optional[str] = Field(None, description="Name of the policy")
    PolicyVersion: Optional[str] = Field(None, description="Version of the policy")
    Port: Optional[str] = Field(None, description="Port that the attacker attempted to access")
    ReportType: Optional[str] = Field(None, description="The nature and impact level of the reported event")
    Service: Optional[str] = Field(None, description="Name of the service the attacker attempted to use")
    SessionId: Optional[int] = Field(None, description="Unique number assigned to a user by a website's server for the duration of the visit or session")
    ShareName: Optional[str] = Field(None, description="Name of the share location that the attacker attempted to access")
    SourceDeviceId: Optional[str] = Field(None, description="Unique identifier for the device that the attack originated from")
    SourceDeviceName: Optional[str] = Field(None, description="Host name of the device where the attack originated from")
    SourceDomainName: Optional[str] = Field(None, description="Domain name of the device where the attack originated from")
    SourceIpAddress: Optional[str] = Field(None, description="IP address where the attacker communication originated from")
    SourcePort: Optional[int] = Field(None, description="Port where the attacker communication originated from")
    SourceSystem: Optional[str] = Field(None, description="The type of agent the event was collected by. For example,OpsManagerfor Windows agent, either direct connect or Operations Manager,Linuxfor all Linux agents, orAzurefor Azure Diagnostics")
    SourceUserDomainName: Optional[str] = Field(None, description="The domain name of the account conducting the malicious activity")
    SourceUserName: Optional[str] = Field(None, description="The user name of the account conducting the malicious activity")
    SourceUserSid: Optional[str] = Field(None, description="The security identifier of the account conducting the malicious activity")
    TargetDeviceId: Optional[str] = Field(None, description="Unique identifier for the device that was targeted or attacked")
    TargetDeviceName: Optional[str] = Field(None, description="Name of the device that was targeted or attacked")
    TargetDomainName: Optional[str] = Field(None, description="Domain name of the device that was targeted or attacked")
    TenantId: Optional[str] = Field(None, description="The Log Analytics workspace ID")
    TimeGenerated: Optional[datetime] = Field(None, description="Date and time the event was recorded by the MDE agent on the endpoint.")
    Type: Optional[str] = Field(None, description="The name of the table")
