from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class EmailAttachmentInfo(BaseModel):
    Timestamp: Optional[datetime] = Field(None, description="Date and time when the event was recorded")
    DetectionMethods: Optional[str] = Field(None, description="Sender email address in the from header, which is visible to email recipients on their email clients.")
    FileExtension: Optional[str] = Field(None, description="File extension of the attachment.")
    FileName: Optional[str] = Field(None, description="Name of the file that the recorded action was applied to.")
    FileSize: Optional[int] = Field(None, description="Size of the file in bytes.")
    FileType: Optional[str] = Field(None, description="File extension type.")
    NetworkMessageId: Optional[str] = Field(None, description="Unique identifier for the email, generated by Office 365.")
    RecipientEmailAddress: Optional[str] = Field(None, description="Email address of the recipient, or email address of the recipient after distribution list expansion.")
    RecipientObjectId: Optional[str] = Field(None, description="Email recipient unique identifier in Azure AD.")
    ReportId: Optional[str] = Field(None, description="Unique identifier for the event.")
    SenderDisplayName: Optional[str] = Field(None, description="Sender email address in the from header, which is visible to email recipients on their email clients.")
    SenderFromAddress: Optional[str] = Field(None, description="Sender domain in the from header, which is visible to email recipients on their email clients.")
    SenderObjectId: Optional[str] = Field(None, description="Sender email address in the from header, which is visible to email recipients on their email clients.")
    SHA256: Optional[str] = Field(None, description="SHA-256 of the file that the recorded action was applied to.")
    SourceSystem: Optional[str] = Field(None, description="The type of agent the event was collected by. For example,OpsManagerfor Windows agent, either direct connect or Operations Manager,Linuxfor all Linux agents, orAzurefor Azure Diagnostics")
    TenantId: Optional[str] = Field(None, description="The Log Analytics workspace ID")
    ThreatNames: Optional[str] = Field(None, description="Sender email address in the from header, which is visible to email recipients on their email clients.")
    ThreatTypes: Optional[str] = Field(None, description="Verdict from the email filtering stack on whether the email contains malware, phishing, or other threats.")
    TimeGenerated: Optional[datetime] = Field(None, description="Date and time (UTC) when the record was generated.")
    Type: Optional[str] = Field(None, description="The name of the table")
