from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class EmailUrlInfo(BaseModel):
    Timestamp: Optional[datetime] = Field(None, description="Date and time when the event was recorded")
    NetworkMessageId: Optional[str] = Field(None, description="Email unique identifier generated by Office 365")
    ReportId: Optional[str] = Field(None, description="Unique identifier for the event")
    SourceSystem: Optional[str] = Field(None, description="The type of agent the event was collected by. For example,OpsManagerfor Windows agent, either direct connect or Operations Manager,Linuxfor all Linux agents, orAzurefor Azure Diagnostics")
    TenantId: Optional[str] = Field(None, description="The Log Analytics workspace ID")
    TimeGenerated: Optional[datetime] = Field(None, description="Date and time (UTC) when the record was generated")
    Type: Optional[str] = Field(None, description="The name of the table")
    Url: Optional[str] = Field(None, description="Information about URLs on Office 365 emails")
    UrlDomain: Optional[str] = Field(None, description="Domain part of the Url")
    UrlLocation: Optional[str] = Field(None, description="Indicates which part of the email the URL is located")
