from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class EmailPostDeliveryEvents(BaseModel):
    Timestamp: Optional[datetime] = Field(None, description="Date and time when the event was recorded")
    Action: Optional[str] = Field(None, description="Action taken on the entity")
    ActionResult: Optional[str] = Field(None, description="Result of the action")
    ActionTrigger: Optional[str] = Field(None, description="Indicates whether an action was triggered by an administrator (manually or through approval of a pending automated action), or by some special mechanism, such as a ZAP or String Delivery")
    ActionType: Optional[str] = Field(None, description="Type of activity that triggered the event")
    DeliveryLocation: Optional[str] = Field(None, description="Delivered email location: Inbox/Folder, On-premises/External, Junk, Quarantine, Failed, Dropped, Deleted items")
    DetectionMethods: Optional[str] = Field(None, description="Methods used to detect malware, phishing, or other threats found in the email")
    EmailDirection: Optional[str] = Field(None, description="Direction of the email relative to your network: Inbound, Outbound, Intra-org")
    InternetMessageId: Optional[str] = Field(None, description="Public-facing identifier for the email that is set by the sending email system")
    NetworkMessageId: Optional[str] = Field(None, description="Email unique identifier generated by Office 365")
    RecipientEmailAddress: Optional[str] = Field(None, description="Recipient email address or email address of the recipient after distribution list expansion")
    ReportId: Optional[str] = Field(None, description="Unique identifier for the event")
    SenderFromAddress: Optional[str] = Field(None, description="Sender email address in the FROM header, which is visible to email recipients on their email clients")
    SourceSystem: Optional[str] = Field(None, description="The type of agent the event was collected by. For example,OpsManagerfor Windows agent, either direct connect or Operations Manager,Linuxfor all Linux agents, orAzurefor Azure Diagnostics")
    TenantId: Optional[str] = Field(None, description="The Log Analytics workspace ID")
    ThreatTypes: Optional[str] = Field(None, description="Verdict from the email filtering stack on whether the email contains malware, phishing, or other threats")
    TimeGenerated: Optional[datetime] = Field(None, description="Date and time (UTC) when the record was generated")
    Type: Optional[str] = Field(None, description="The name of the table")
