from datetime import datetime
from typing import Any
from typing import Optional

from pydantic import BaseModel, Field


class IdentityAccountInfo(BaseModel):
    AccountId: Optional[str] = Field(None, description="Internal identifier for the account.")
    AccountStatus: Optional[str] = Field(None, description="The status of the account.")
    AccountUpn: Optional[str] = Field(None, description="User principal name (UPN) of the account.")
    AdditionalFields: Optional[Any] = Field(None, description="Additional information about the entity or event.")
    Address: Optional[str] = Field(None, description="Address of the account user.")
    AssignedRoles: Optional[Any] = Field(None, description="Role identifiers assigned to the account.")
    AuthenticationMethod: Optional[str] = Field(None, description="Authentication method used to allow the account user to sign in.")
    AuthenticationSourceAcccountId: Optional[str] = Field(None, description="Identifier of the federating account, if authentication method is Federated.")
    City: Optional[str] = Field(None, description="City where the account user is located.")
    Country: Optional[str] = Field(None, description="Country or region where the account user is located.")
    CreatedDateTime: Optional[datetime] = Field(None, description="Date and time when the user account was created.")
    CriticalityLevel: Optional[int] = Field(None, description="The criticality score of the account.")
    DefenderRiskLevel: Optional[int] = Field(None, description="The risk level of the account as calculated by Microsoft Defender.")
    DefenderRiskUpdateTime: Optional[datetime] = Field(None, description="Date and time Microsoft Defender last updated the risk level of the account.")
    DeletedDateTime: Optional[datetime] = Field(None, description="Date and time when the user account was deleted.")
    Department: Optional[str] = Field(None, description="Name of the department that the account user belongs to.")
    DisplayName: Optional[str] = Field(None, description="Name of the account user displayed in the address book.")
    EligibleRoles: Optional[Any] = Field(None, description="Identifiers for roles the account is eligible to use.")
    EmailAddress: Optional[str] = Field(None, description="SMTP address of the account.")
    EmployeeId: Optional[str] = Field(None, description="Employee identifier assigned to the user by the organization.")
    EnrolledMfas: Optional[Any] = Field(None, description="Configured multifactor authentication methods and status.")
    GivenName: Optional[str] = Field(None, description="Given name or first name of the account user.")
    GroupMembership: Optional[Any] = Field(None, description="Group identifiers assigned to the account.")
    IdentityId: Optional[str] = Field(None, description="Identifier for the identity that the account is linked to.")
    IdentityLinkBy: Optional[str] = Field(None, description="The entity that linked the account to the identity.")
    IdentityLinkReason: Optional[str] = Field(None, description="Reason for linking the account and identity.")
    IdentityLinkTime: Optional[datetime] = Field(None, description="Date and time the account was linked to the identity.")
    IdentityLinkType: Optional[str] = Field(None, description="Type of linkage between the account and identity.")
    IdentityType: Optional[str] = Field(None, description="Type of identity - possible values: User, ServiceAccount")
    IsPrimary: Optional[bool] = Field(None, description="Indicates if this account is considered as primary account for the linked identity.")
    JobTitle: Optional[str] = Field(None, description="Job title of the account user.")
    LastPasswordChangeTime: Optional[datetime] = Field(None, description="Date and time the account password was last changed.")
    Manager: Optional[str] = Field(None, description="The listed manager of the account user.")
    Phone: Optional[str] = Field(None, description="The listed phone number of the account user.")
    ReportId: Optional[str] = Field(None, description="Unique identifier for the event.")
    Sid: Optional[str] = Field(None, description="Security identifier (SID) of the account.")
    SourceProvider: Optional[str] = Field(None, description="Source application or service of the account.")
    SourceProviderAccountId: Optional[str] = Field(None, description="Identifier for the account in the source provider.")
    SourceProviderInstanceDisplayName: Optional[str] = Field(None, description="Display name of the source application or service of the account.")
    SourceProviderInstanceId: Optional[str] = Field(None, description="Identifier of the source application or service of the account.")
    SourceProviderRiskLevel: Optional[Any] = Field(None, description="Risk level of the account as it appears in the source provider.")
    SourceSystem: Optional[str] = Field(None, description="The type of agent the event was collected by. For example,OpsManagerfor Windows agent, either direct connect or Operations Manager,Linuxfor all Linux agents, orAzurefor Azure Diagnostics")
    Surname: Optional[str] = Field(None, description="Surname, family name, or last name of the account user.")
    Tags: Optional[Any] = Field(None, description="Tags assigned to the account by Defender for Identity.")
    TenantId: Optional[str] = Field(None, description="The Log Analytics workspace ID")
    TenantMembershipType: Optional[str] = Field(None, description="User type.")
    TimeGenerated: Optional[datetime] = Field(None, description="Date and time (UTC) when the record was generated")
    Timestamp: Optional[datetime] = Field(None, description="Date and time that the line was written to the database.")
    Type: Optional[str] = Field(None, description="The name of the table")
