from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class MessageUrlInfo(BaseModel):
    Timestamp: Optional[datetime] = Field(None, description="Date and time when the event was recorded")
    ReportId: Optional[str] = Field(None, description="Unique identifier for the event")
    SourceSystem: Optional[str] = Field(None, description="The type of agent the event was collected by. For example,OpsManagerfor Windows agent, either direct connect or Operations Manager,Linuxfor all Linux agents, orAzurefor Azure Diagnostics")
    TeamsMessageId: Optional[str] = Field(None, description="Unique identifier for the message, as generated by Microsoft 365")
    TenantId: Optional[str] = Field(None, description="The Log Analytics workspace ID")
    ThreatTypes: Optional[str] = Field(None, description="Verdict from the filtering stack on whether the message contains malware, phishing, or other threats")
    TimeGenerated: Optional[datetime] = Field(None, description="Date and time (UTC) when the record was generated.")
    Type: Optional[str] = Field(None, description="The name of the table")
    Url: Optional[str] = Field(None, description="URL from message")
    UrlDomain: Optional[str] = Field(None, description="Domain name or host name of the URL")
