from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class MessageUrlInfo(BaseModel):
    Timestamp: Optional[datetime] = Field(None, description="Date and time when the event was recorded")
    TeamsMessageId: Optional[str] = Field(None, description="Unique identifier for the message, as generated by Microsoft 365")
    Url: Optional[str] = Field(None, description="URL from message")
    UrlDomain: Optional[str] = Field(None, description="Domain name or host name of the URL")
    ThreatTypes: Optional[str] = Field(None, description="Verdict from the filtering stack on whether the message contains malware, phishing, or other threats")
    ReportId: Optional[str] = Field(None, description="Unique identifier for the event")
