from datetime import datetime
from typing import Any
from typing import Optional

from pydantic import BaseModel, Field


class MessageEvents(BaseModel):
    Timestamp: Optional[datetime] = Field(None, description="Date and time when the event was recorded")
    ConfidenceLevel: Optional[Any] = Field(None, description="List of confidence levels for each threat type identified")
    DeliveryAction: Optional[str] = Field(None, description="Delivery action of the message: Delivered, Blocked")
    DeliveryLocation: Optional[str] = Field(None, description="Location of the message at the time of delivery")
    DetectionMethods: Optional[Any] = Field(None, description="Methods used to detect malware, phishing, or other threats found in the message")
    GroupId: Optional[str] = Field(None, description="Identifier for the team or group that the message was sent to")
    GroupName: Optional[str] = Field(None, description="Name of the team or group that the message was sent to")
    IsExternalThread: Optional[bool] = Field(None, description="Indicates if there are external recipients in the thread (1) or none (0)")
    IsOwnedThread: Optional[bool] = Field(None, description="Boolean value indicating whether the message is owned by your organization or not (only the messages owned by your organization can be remediated)")
    LastEditedTime: Optional[str] = Field(None, description="Date and time when the message was last edited")
    MessageFormatSubtype: Optional[str] = Field(None, description="Subtype of message format, for example, HTML")
    MessageFormatType: Optional[str] = Field(None, description="Type of message format; possible values: RichText, Text")
    MessageId: Optional[str] = Field(None, description="Identifier for the message (non-unique)")
    MessageSubject: Optional[str] = Field(None, description="Subject of the message, if it exists")
    MessageVersion: Optional[str] = Field(None, description="Version number of the message")
    ParentMessageId: Optional[str] = Field(None, description="Identifier for the message that the current message was a reply to, otherwise this is the same as the MessageId")
    RecipientDetails: Optional[Any] = Field(None, description="Array of recipient data (RecipientSmtpAddress, RecipientDisplayName, RecipientType, RecipientObjectId)")
    ReportId: Optional[str] = Field(None, description="Unique identifier for the event")
    SafetyTip: Optional[str] = Field(None, description="The safety tip that has been added on a message, if any")
    SenderDisplayName: Optional[str] = Field(None, description="Name of the sender displayed in the address book, typically a combination of a first name, a middle initial, and a last name or surname")
    SenderEmailAddress: Optional[str] = Field(None, description="Email address of the sender")
    SenderObjectId: Optional[str] = Field(None, description="Unique identifier for the sender's account")
    SenderType: Optional[str] = Field(None, description="Type of user that sent the message, for example, User, Group, Anonymous")
    SourceSystem: Optional[str] = Field(None, description="The type of agent the event was collected by. For example,OpsManagerfor Windows agent, either direct connect or Operations Manager,Linuxfor all Linux agents, orAzurefor Azure Diagnostics")
    TeamsMessageId: Optional[str] = Field(None, description="Unique identifier for the message, as generated by Microsoft 365")
    TenantId: Optional[str] = Field(None, description="The Log Analytics workspace ID")
    ThreadId: Optional[str] = Field(None, description="Identifier of the channel or chat thread that the message is part of")
    ThreadSubtype: Optional[str] = Field(None, description="Indicates the channel type, possible values: None, PrivateChannel")
    ThreatTypes: Optional[str] = Field(None, description="Verdict from the filtering stack on whether the message contains malware, phishing, or other threats")
    TimeGenerated: Optional[datetime] = Field(None, description="Date and time (UTC) when the record was generated.")
    Type: Optional[str] = Field(None, description="The name of the table")
