from datetime import datetime
from typing import Any
from typing import Optional

from pydantic import BaseModel, Field


class MessageEvents(BaseModel):
    Timestamp: Optional[datetime] = Field(
        None, description="Date and time when the event was recorded"
    )
    LastEditedTime: Optional[str] = Field(
        None, description="Date and time when the message was last edited"
    )
    TeamsMessageId: Optional[str] = Field(
        None,
        description="Unique identifier for the message, as generated by Microsoft 365",
    )
    SenderEmailAddress: Optional[str] = Field(
        None, description="Email address of the sender"
    )
    SenderDisplayName: Optional[str] = Field(
        None,
        description="Name of the sender displayed in the address book, typically a combination of a first name, a middle initial, and a last name or surname",
    )
    SenderObjectId: Optional[str] = Field(
        None, description="Unique identifier for the senderâs account"
    )
    SenderType: Optional[str] = Field(
        None,
        description="Type of user that sent the message, for example, User, Group, Anonymous",
    )
    RecipientDetails: Optional[Any] = Field(
        None,
        description="Array of recipient data (RecipientSmtpAddress, RecipientDisplayName, RecipientType, RecipientObjectId)",
    )
    IsOwnedThread: Optional[bool] = Field(
        None,
        description="Boolean value indicating whether the message is owned by your organization or not (only the messages owned by your organization can be remediated)",
    )
    MessageId: Optional[str] = Field(
        None, description="Identifier for the message (non-unique)"
    )
    ParentMessageId: Optional[str] = Field(
        None,
        description="Identifier for the message that the current message was a reply to, otherwise this is the same as the MessageId",
    )
    GroupId: Optional[str] = Field(
        None,
        description="Identifier for the team or group that the message was sent to",
    )
    GroupName: Optional[str] = Field(
        None, description="Name of the team or group that the message was sent to"
    )
    ThreadId: Optional[str] = Field(
        None,
        description="Identifier of the channel or chat thread that the message is part of",
    )
    ThreadSubtype: Optional[str] = Field(
        None,
        description="Indicates the channel type, possible values: None, PrivateChannel",
    )
    IsExternalThread: Optional[bool] = Field(
        None,
        description="Indicates if there are external recipients in the thread (1) or none (0)",
    )
    MessageFormatType: Optional[str] = Field(
        None, description="Type of message format; possible values: RichText, Text"
    )
    MessageFormatSubtype: Optional[str] = Field(
        None, description="Subtype of message format, for example, HTML"
    )
    MessageVersion: Optional[str] = Field(
        None, description="Version number of the message"
    )
    MessageSubject: Optional[str] = Field(
        None, description="Subject of the message, if it exists"
    )
    ThreatTypes: Optional[str] = Field(
        None,
        description="Verdict from the filtering stack on whether the message contains malware, phishing, or other threats",
    )
    DetectionMethods: Optional[Any] = Field(
        None,
        description="Methods used to detect malware, phishing, or other threats found in the message",
    )
    ConfidenceLevel: Optional[Any] = Field(
        None, description="List of confidence levels for each threat type identified"
    )
    DeliveryAction: Optional[str] = Field(
        None, description="Delivery action of the message: Delivered, Blocked"
    )
    DeliveryLocation: Optional[str] = Field(
        None, description="Location of the message at the time of delivery"
    )
    ReportId: Optional[str] = Field(None, description="Unique identifier for the event")
    SafetyTip: Optional[str] = Field(
        None, description="The safety tip that has been added on a message, if any"
    )
