from datetime import datetime
from typing import Any
from typing import Optional

from pydantic import BaseModel, Field


class MessagePostDeliveryEvents(BaseModel):
    Timestamp: Optional[datetime] = Field(None, description="Date and time when the event was recorded")
    TeamsMessageId: Optional[str] = Field(None, description="Unique identifier for the message, as generated by Microsoft 365")
    Action: Optional[str] = Field(None, description="Action taken on the message: Blocked, Moved to quarantine")
    ActionType: Optional[str] = Field(None, description="Type of activity that triggered the event: Manual remediation, Phish ZAP, Malware ZAP")
    ActionTrigger: Optional[str] = Field(None, description="Indicates whether an action was triggered by an administrator (manually or through approval of a pending automated action), or by some special mechanism, such as a ZAP or Dynamic Delivery")
    ActionResult: Optional[str] = Field(None, description="Result of the action")
    SenderEmailAddress: Optional[str] = Field(None, description="Email address of the sender")
    RecipientDetails: Optional[Any] = Field(None, description="Array of recipient data (RecipientSmtpAddress, RecipientDisplayName, RecipientType, RecipientObjectId)")
    ThreatTypes: Optional[str] = Field(None, description="Verdict from the filtering stack on whether the message contains malware, phishing, or other threats")
    ConfidenceLevel: Optional[Any] = Field(None, description="List of confidence levels for each threat type identified")
    DetectionMethods: Optional[str] = Field(None, description="Methods used to detect malware, phishing, or other threats found in the message")
    LatestDeliveryLocation: Optional[str] = Field(None, description="Last known location of the message")
    ReportId: Optional[str] = Field(None, description="Unique identifier for the event")
    IsExternalThread: Optional[bool] = Field(None, description="Indicates if there are external recipients in the thread (1) or none (0)")
    SafetyTip: Optional[str] = Field(None, description="The safety tip that has been added on a message, if any")
