from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class UrlClickEvents(BaseModel):
    AccountUpn: Optional[str] = Field(None, description="User Principal Name of the account that clicked on the link.")
    ActionType: Optional[str] = Field(None, description="Indicates whether the click was allowed or blocked by 'safe links' or blocked due to a tenant policy e.g., from tenant allow block list.")
    AppName: Optional[str] = Field(None, description="The application's display name as exposed by the associated service principal.")
    AppVersion: Optional[str] = Field(None, description="Version of the client application where click occurred")
    DetectionMethods: Optional[str] = Field(None, description="Detection technology which was used to identify the threat at the time of click.")
    IPAddress: Optional[str] = Field(None, description="Public IP address of the device from which the user clicked on the link.")
    IsClickedThrough: Optional[bool] = Field(None, description="Indicates whether the user was able to click through to the original URL or was not allowed.")
    NetworkMessageId: Optional[str] = Field(None, description="The unique identifier for the email that contains the clicked link, generated by Microsoft 365.")
    ReportId: Optional[str] = Field(None, description="This is the unique identifier for a click event. Note that for clickthrough scenarios, report ID would have same value, and therefore it should be used to correlate a click event.")
    SourceId: Optional[str] = Field(None, description="Unique identifier for the source of the click")
    SourceSystem: Optional[str] = Field(None, description="The type of agent the event was collected by. For example,OpsManagerfor Windows agent, either direct connect or Operations Manager,Linuxfor all Linux agents, orAzurefor Azure Diagnostics")
    TenantId: Optional[str] = Field(None, description="The Log Analytics workspace ID")
    ThreatTypes: Optional[str] = Field(None, description="Verdict at the time of click, which tells whether the URL led to malware, phish or other threats.")
    TimeGenerated: Optional[datetime] = Field(None, description="The date and time when the user clicked on the link. The value is identical to TimeGenerated and intended for Microsoft Defender for Endpoints queries compatibility.")
    Type: Optional[str] = Field(None, description="The name of the table")
    Url: Optional[str] = Field(None, description="The full URL that was clicked on by the user.")
    UrlChain: Optional[str] = Field(None, description="For scenarios involving redirections, it includes URLs present in the redirection chain.")
    Workload: Optional[str] = Field(None, description="The application from which the user clicked on the link, with the values being Email, Office and Teams.")
